services:
  mysql:
    container_name: 'customerConnect_db'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=customerConnectDb'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'